PlaceOS/local

- install
- restart
- scripts/generate-minimal-entities.sh
Includes some changes to align the install and restart scripts
> style: small output format changes, pass/fail for auth creation

- README.md
- docker-compose.yml
- install
- restart
- Added frontends service to docker-compose.yml
- Created a www volume in docker-compose.yml
- Removed git submodule update from restart script
- Removed pulling of `www` repo in `install` and `restart`
- Removed pulling of `drivers` repo in `install` and `restart`
> feat(service:frontends): add `frontends` service

- .env
- docker-compose.yml
- restart
- scripts/run-sam-task
- add`scripts/rum-sam-task` for one-off cluster tasks defined in `init`
- add YAML anchors (dry it up)
- add variable substitution (configure image tags via `.env`)
> refactor(docker-compose): variable substitution and YAML anchors

- .env
- docker-compose.yml
- Add `x-place-loader-client-env` YAML anchor
- Add `x-rubber-soul-client-env` YAML anchor
- Add `RUBBER_SOUL_URI` to `rest-api`
> feat(docker-compose): add rubber-soul client variables

- install
- scripts/generate-secrets
- scripts/init-influxdb
pass a generated api key to influxdb on start up
> fix: generate api key

- docker-compose.yml
Pass place domain env var to the nginx container for SSL cert generation.
> fix: missing ssl certs

- docker-compose.yml
> Remove static IP from init container

- config/nginx/nginx.conf
Resolves https://github.com/PlaceOS/nginx/issues/3
> fix(nginx): deny requests to any .git contents

- .github/workflows/ci.yml
Adds CI to ensure the environment can be initialised.
> ci: test environment initialization

- placeos
- scripts/spinner.sh
cuter spinner with these frames `⠇⠋⠙⠸⠴⠦`
> style: use nicer spinner

- docker-compose.yml
Relaxes the docker-compose enforced dependency between services.
Related #57
> build: remove strong dependency between services

- .github/workflows/ci.yml
Adds a test for systems without `PLACEOS_TAG` defined in its environment
> ci: test empty `PLACEOS_TAG`

- .env
- .github/workflows/ci.yml
Updates default service versions to `placeos-1.2108.4`.
> build: placeos-1.2108.4

- .env
- .github/workflows/ci.yml
Updates the environment to [`placeos-1.2109.1`](https://github.com/PlaceOS/PlaceOS/blob/nightly/CHANGELOG.md#121091)
> build: update to `placeos-1.2109.1`

- README.md
Added a note on a gotcha with memory and the docker for mac platform
> docs(README): note on memory on docker for mac

- .env
- .github/workflows/ci.yml
- docker-compose.yml
- placeos
Closes #87 
Closes https://github.com/PlaceOS/init/issues/52
- Removed `data` folder
- Adds broken 1.2111.3 version to CI  matrix
- Removed default secret from `.env`
> fix: forward environment

- .env
- .github/workflows/ci.yml
[See CHANGELOG here](https://github.com/PlaceOS/PlaceOS/blob/1.2201/CHANGELOG.md#122010)
> Release: 1.2201.1

- docker-compose.yml
- placeos
- scripts/init-influxdb
- scripts/metricbeat
- scripts/start-services
- scripts/watch-crystal
Small syntactic change to reduce repetition
> refactor: network anchor

- docker-compose.yml
Add healthchecks for nginx and postgres
closes https://github.com/place-labs/partner-environment/issues/61
> feat(docker-compose): add healthchecks to postgres and nginx

- docker-compose.yml
Use a more stable default for tags in `docker-compose.yml`
> build(docker-compose): default to `latest` instead of `nightly`

- README.md
- placeos
**Description of the change**
Render the `PLACEOS_TAG` in use with `$ placeos version` or `$ placeos --version`
> feat(placeos): add `version` command

- README.md
- placeos
- scripts/install
**Description of the change**
Closes #110 
The repository should be renamed _before_ the merge of these changes.
> refactor: rename to `PlaceOS Local`

- .env
- docker-compose.yml
**Description of the change**
Adds OpenTelemetry environment variables to `docker-compose.yml`
**Applicable issues**
- https://github.com/PlaceOS/PlaceOS/issues/135
> feat(docker-compose): add OpenTelemetry environment

- .env
- .github/workflows/ci.yml
> chore: update to `placeos-1.2205.0`

- .env
- .github/workflows/ci.yml
**Description of the change**
Update to the latest platform version
> build: update to 1.2205.1

- docker-compose.yml
- scripts/generate-secrets
When deploying to production we'll also have to add the SECRET_KEY_BASE env var to nginx
> feat: changes required to support protected assets
